### ISSUE TITLE
Add option to keep open with a single keypress

### ISSUE THREAD

**Issue by alpipego** [riccqi/TabTabApp#2]
Instead of having to hit “Enter” after Cmd/Opt+Tab, I would appreciate it if it had an option to go into search mode immediately (Contexts can do this). For one, it would save me keystrokes, but secondly, I have an app called [CheatSheet](https://cheatsheet-mac.en.softonic.com/mac) installed that shows all keyboard shortcuts for an app when holding the Cmd key. The pop-up by CheatSheet overlays the TabTab pop-up and it's frustrating.

**Comment by riccqi** [comment]
great suggestion. i'll look into this.

for the overlay blocking part, would it solve your problem if the Tab Bar was instead presented in the center or the right side of the screen?

**Comment by alpipego** [comment]
> for the overlay blocking part, would it solve your problem if the Tab Bar was instead presented in the center or the right side of the screen?

No, that would not matter. Thanks for the suggestion. The CheatSheet overlay is centered but takes up ~90% of the horizontal space.

**Comment by riccqi** [comment]
this has been added in update 1.2. 

you can just click CMD+K to open up the tab bar with search already opened.

you can also change the hotkey in settings :)
